server:
  port: 8087

logging:
  level:
    root: info

spring:
  dubbo:
    application: gmall-payment
    registry:
      address: 192.168.124.129:2181
      protocol: zookeeper
    protocol:
      name: dubbo
    base-package: com.rufeng2333.gmall
    consumer:
      timeout: 600000
      check: false
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    password: 5110
  redis:
    host: 192.168.124.129
    port: 6379
    database: 0
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  activemq:
    broker-url: tcp://localhost:61616

activemq:
  listener:
    enable: true

  mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: true