spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    password: 5110

  #提供者
  dubbo:
    application: manage-service
    registry:
      address: 192.168.124.129:2181
      protocol: zookeeper
    protocol:
      name: dubbo
    base-package: com.rufeng2333.gmall

server:
  port: 8071

logging:
  level:
    root: info